name: Linux RDP via Tailscale (airaacheisyaa)

on:
  workflow_dispatch:

jobs:
  rdp-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Desktop Environment and RDP Server
        run: |
          sudo apt-get update
          export DEBIAN_FRONTEND=noninteractive
          # Instalasi tetap lengkap untuk memastikan semua ada
          sudo apt-get install -y xfce4 desktop-base xfce4-goodies dbus-x11 xorg xrdp xorgxrdp
          sudo adduser xrdp ssl-cert
          
          # --- SOLUSI FUNDAMENTAL ---
          # Konfigurasi xrdp untuk menggunakan skrip session manager utama sistem,
          # yang kompatibel dengan lingkungan tanpa systemd.
          sudo tee /etc/xrdp/startwm.sh > /dev/null << EOT
          #!/bin/sh
          # Menjalankan skrip Xsession bawaan sistem. Ini adalah kunci utamanya.
          # Skrip ini akan mengatur seluruh environment sesi dengan benar.
          exec /etc/X11/Xsession
          EOT
          
          sudo chmod +x /etc/xrdp/startwm.sh
          sudo systemctl restart xrdp

      - name: Create User and Set Static Password
        run: |
          USERNAME="airaacheisyaa"
          PASSWORD="airaacheisyaa123"
          echo "RDP_PASSWORD=${PASSWORD}" >> $GITHUB_ENV
          
          sudo useradd -m -s /bin/bash "${USERNAME}"
          sudo adduser "${USERNAME}" sudo
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          
          # --- KONFIGURASI PENDUKUNG ---
          # Buat file .xsession di home directory pengguna.
          # Skrip /etc/X11/Xsession akan mencari dan mengeksekusi file ini.
          echo "xfce4-session" | sudo tee "/home/${USERNAME}/.xsession"
          sudo chown "${USERNAME}:${USERNAME}" "/home/${USERNAME}/.xsession"
          
          echo "Pengguna '${USERNAME}' berhasil dibuat dan dikonfigurasi."

      - name: Install and Connect Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-linux-$GITHUB_RUN_ID --ssh
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: Display Connection Details and Keep Alive
        run: |
          echo ""
          echo "====================== RDP ACCESS LINUX ======================"
          echo "Alamat RDP (IP) : ${{ env.TAILSCALE_IP }}"
          echo "Username        : airaacheisyaa"
          echo "Password        : ${{ env.RDP_PASSWORD }}"
          echo "=============================================================="
          echo "Runner akan tetap aktif. Tekan Ctrl+C di log Actions untuk menghentikan."
          sleep infinity
