name: Linux RDP via Tailscale (airaacheisyaa)

on:
  workflow_dispatch:

jobs:
  rdp-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Desktop Environment and RDP Server
        run: |
          sudo apt-get update
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get install -y xfce4 desktop-base xfce4-goodies dbus-x11 xorg xrdp
          sudo adduser xrdp ssl-cert
          
          # --- PERBAIKAN UTAMA (PLAN B) ---
          # Ganti total isi skrip startup XRDP untuk memastikan XFCE berjalan.
          # Ini adalah metode yang paling andal.
          sudo tee /etc/xrdp/startwm.sh > /dev/null << EOT
          #!/bin/sh
          # Pastikan environment bersih sebelum memulai sesi
          unset DBUS_SESSION_BUS_ADDRESS
          unset XDG_RUNTIME_DIR

          # Mulai XFCE dengan D-Bus
          dbus-launch --exit-with-session xfce4-session
          EOT
          
          # Pastikan skrip baru dapat dieksekusi
          sudo chmod +x /etc/xrdp/startwm.sh
          
          # Restart layanan XRDP untuk menerapkan perubahan skrip
          sudo systemctl restart xrdp

      - name: Create User and Set Static Password
        run: |
          # Atur username dan password yang diinginkan
          USERNAME="airaacheisyaa"
          PASSWORD="airaacheisyaa123"
          
          echo "RDP_PASSWORD=${PASSWORD}" >> $GITHUB_ENV
          
          # Buat pengguna baru (tidak perlu lagi membuat file .xsession)
          sudo useradd -m -s /bin/bash "${USERNAME}"
          sudo adduser "${USERNAME}" sudo
          echo "${USERNAME}:${PASSWORD}" | sudo chpasswd
          
          echo "Pengguna '${USERNAME}' berhasil dibuat."

      - name: Install and Connect Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-linux-$GITHUB_RUN_ID --ssh
          echo "TAILSCALE_IP=$(tailscale ip -4)" >> $GITHUB_ENV

      - name: Display Connection Details and Keep Alive
        run: |
          echo ""
          echo "====================== RDP ACCESS LINUX ======================"
          echo "Alamat RDP (IP) : ${{ env.TAILSCALE_IP }}"
          echo "Username        : airaacheisyaa"
          echo "Password        : ${{ env.RDP_PASSWORD }}"
          echo "=============================================================="
          echo "Runner akan tetap aktif. Tekan Ctrl+C di log Actions untuk menghentikan."
          
          sleep infinity
